### PR TITLE
Generalise check_perams.py and refine output

### PR DESCRIPTION
**Pull request by kostrzewa**

### CODE REVIEW

**Comment by kostrzewa** [comment]
@chelmes  Any preferences on Pythonic indentation? I use two spaces, but I can switch to four if you prefer.

**Comment by kostrzewa** [comment]
I've also added an option to ```tar_perams_ranged.py``` which performs the rsync "on the fly", thus saving temporary space.

**Comment by maowerner** [comment]
I prefer two spaces as well, but I don't even consequently enforce this in my own code -> I'm fine with both. The "on the fly" option is indeed very useful :)

**Comment by kostrzewa** [comment]
@chelmes it would be nice if you could review this and pull it in, if you agree

**Pull request merged**
